# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

em_with_zero_mean_c <- function(y, maxit) {
    .Call(`_MCMCArmadillo_em_with_zero_mean_c`, y, maxit)
}

mvrnormArma <- function(n, mu, Sigma) {
    .Call(`_MCMCArmadillo_mvrnormArma`, n, mu, Sigma)
}

dmvnrm_arma <- function(x, mean, sigma, logd = FALSE) {
    .Call(`_MCMCArmadillo_dmvnrm_arma`, x, mean, sigma, logd)
}

get_sigmabeta_from_h_c <- function(h, gam, Sigma, X, T) {
    .Call(`_MCMCArmadillo_get_sigmabeta_from_h_c`, h, gam, Sigma, X, T)
}

get_h_from_sigmabeta_c <- function(X, sigmabeta, Sigma, gam, n, T) {
    .Call(`_MCMCArmadillo_get_h_from_sigmabeta_c`, X, sigmabeta, Sigma, gam, n, T)
}

get_target_c <- function(X, Y, sigmabeta, Sigma, gam, beta) {
    .Call(`_MCMCArmadillo_get_target_c`, X, Y, sigmabeta, Sigma, gam, beta)
}

sample_index <- function(size, prob = as.numeric( c())) {
    .Call(`_MCMCArmadillo_sample_index`, size, prob)
}

update_gamma_c <- function(X, Y, gam) {
    .Call(`_MCMCArmadillo_update_gamma_c`, X, Y, gam)
}

betagam_accept_c <- function(X, Y, sigmabeta1, inputSigma, Vbeta, gam1, beta1, gam2, beta2, changeind, change) {
    .Call(`_MCMCArmadillo_betagam_accept_c`, X, Y, sigmabeta1, inputSigma, Vbeta, gam1, beta1, gam2, beta2, changeind, change)
}

update_betagam_c <- function(X, Y, gam1, beta1, Sigma, sigmabeta, Vbeta, bgiter) {
    .Call(`_MCMCArmadillo_update_betagam_c`, X, Y, gam1, beta1, Sigma, sigmabeta, Vbeta, bgiter)
}

update_h_c <- function(initialh, hiter, gam, beta, Sig, X, T) {
    .Call(`_MCMCArmadillo_update_h_c`, initialh, hiter, gam, beta, Sig, X, T)
}

rinvwish_c <- function(n, v, S) {
    .Call(`_MCMCArmadillo_rinvwish_c`, n, v, S)
}

update_Sigma_c <- function(n, nu, X, beta, Phi, Y) {
    .Call(`_MCMCArmadillo_update_Sigma_c`, n, nu, X, beta, Phi, Y)
}

update_gamma_sw_c <- function(X, Y, gam, marcor) {
    .Call(`_MCMCArmadillo_update_gamma_sw_c`, X, Y, gam, marcor)
}

betagam_accept_sw_c <- function(X, Y, sigmabeta1, inputSigma, Vbeta, gam1, beta1, gam2, beta2, changeind, change) {
    .Call(`_MCMCArmadillo_betagam_accept_sw_c`, X, Y, sigmabeta1, inputSigma, Vbeta, gam1, beta1, gam2, beta2, changeind, change)
}

update_betagam_sw_c <- function(X, Y, gam1, beta1, Sigma, marcor, sigmabeta, Vbeta, bgiter, smallworlditer) {
    .Call(`_MCMCArmadillo_update_betagam_sw_c`, X, Y, gam1, beta1, Sigma, marcor, sigmabeta, Vbeta, bgiter, smallworlditer)
}

doMCMC_c <- function(X, Y, n, T, Phi, nu, initialbeta, initialgamma, initialSigma, initialsigmabeta, marcor, Vbeta, niter, bgiter, hiter, switer) {
    .Call(`_MCMCArmadillo_doMCMC_c`, X, Y, n, T, Phi, nu, initialbeta, initialgamma, initialSigma, initialsigmabeta, marcor, Vbeta, niter, bgiter, hiter, switer)
}

run2chains_c <- function(X, Y, initial_chain1, initial_chain2, Phi, niter = 1000L, bgiter = 500L, hiter = 50L, switer = 50L, burnin = 5L) {
    .Call(`_MCMCArmadillo_run2chains_c`, X, Y, initial_chain1, initial_chain2, Phi, niter, bgiter, hiter, switer, burnin)
}

